#1684 [Survey] fix: refresh photo ref in banner after add photo
Evarisk/DigiQuali pull request #1777
Opened 2024-03-21 11:05 UTC by evarisk-micka

2024-03-22 18:36 UTC, nicolas-eoxia requested changes

2024-03-22 18:36 UTC, nicolas-eoxia commented on view/survey/survey_card.php
> +$object->fetch(GETPOST('id'));
Ceci ne peux pas être le bon fix cette ligne ce passe déjà avant

Il regarder le refresh dynamique de l'action js et regarder si tout les paramètres sont bien la ou si le bon élément est refresh

2024-04-11 08:17 UTC, evarisk-micka commented on view/survey/survey_card.php
> +$object->fetch(GETPOST('id'));
C'est le bon fix c'est ainsi que l'on fait fonctionner sur le control
L'action JS fonctionne bien tout comme le refresh dynamique

2024-04-12 07:29 UTC, evarisk-micka commented
This is the way we do in control

2024-05-22 07:44 UTC, closed without merging