#1749 [Control] add: csslist on control to reduce fk_sheet column size
Evarisk/DigiQuali pull request #1786
Opened 2024-04-03 13:08 UTC by evarisk-micka

2024-04-12 11:56 UTC, nicolas-eoxia requested changes

2024-04-12 11:56 UTC, nicolas-eoxia commented on core/tpl/digiquali_control_list.tpl.php
> +			print $sheet->selectSheetList(GETPOST('fromtype') == 'fk_sheet' ? GETPOST('fromid') : ($search['fk_sheet'] ?: 0), 'search_fk_sheet', 's.type = ' . '"' . $object->element . '"', '1', 0, 0, [], '',
Je suis d'accord dans le principe sauf que la on veut set les paramètres par défaut du champs ducoup il vaut mieux le faire dans la fonction directement 

Le but de ce genre de paramètres moreCSS c'est d'ajouter du spécifique

2024-04-12 11:56 UTC, nicolas-eoxia commented on view/control/control_list.php
> +            'css'     => (empty($val['csslist']) ? (empty($val['css']) ? '' : $val['css']) : $val['csslist'])
C'est la ligne du module builder ?

2024-06-26 09:22 UTC, evarisk-micka commented on view/control/control_list.php
> +            'css'     => (empty($val['csslist']) ? (empty($val['css']) ? '' : $val['css']) : $val['csslist'])
oui c'est la ligne qui est utilisé partout

2024-06-26 09:23 UTC, evarisk-micka commented on core/tpl/digiquali_control_list.tpl.php
> +			print $sheet->selectSheetList(GETPOST('fromtype') == 'fk_sheet' ? GETPOST('fromid') : ($search['fk_sheet'] ?: 0), 'search_fk_sheet', 's.type = ' . '"' . $object->element . '"', '1', 0, 0, [], '',
C'est un spécifique justement parcequ'on veut limiter la taille seulement dans la liste mais si on utilise la fonction ailleurs et qu'on la veut plus grande alors on veut pas que ce soit du css par défaut

2025-01-07 13:03 UTC, closed without merging