#1788 [Question] add: description field on question list
Evarisk/DigiQuali pull request #1804
Opened 2024-05-13 07:27 UTC by evarisk-charles

2024-05-15 12:21 UTC, nicolas-eoxia requested changes
Il faut repositionner la description au bon endroit et voir s'il y'a pas d'impact sur la view

2024-08-28 07:25 UTC, evarisk-micka requested changes

2024-08-28 07:25 UTC, evarisk-micka commented on class/question.class.php
> +     * @param  int    $mode   0 = long label, 1 = shot label, 2 = Picto + short label, 3 = Picto, 4 = Picto + long label, 5 = Short label + Picto, 6 = Long label + Picto
non c'est bien short et pas shot

2024-08-28 07:25 UTC, evarisk-micka commented on class/question.class.php
> +		'description'            => ['type' => 'html',         'label' => 'Description',          'enabled' => 1, 'position' => 12, 'notnull' => 0, 'visible' => 1],
Si la position de description et de label sont 11 et 12 alors il faut les monter en dessous de ref dont la position est 10 afin de rester cohérent

2024-08-28 07:25 UTC, evarisk-micka commented on view/question/question_list.php
> +$parameters = ['arrayfields'=>$arrayfields, 'param'=>$param, 'sortfield'=>$sortfield, 'sortorder'=>$sortorder];
psr12

2024-08-28 07:25 UTC, evarisk-micka commented on view/question/question_list.php
> +        var_dump($val);
oh non pas ça...

2024-08-28 07:43 UTC, evarisk-micka approved these changes

2024-08-28 07:47 UTC, merged